name: Basic check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: cargo fmt --check --verbose
    - name: Linting
      run: cargo clippy
    - name: Doc
      run: cargo test --doc
    - name: Build
      run: cargo build --verbose
